- frontend/db.json
- frontend/package.json
- frontend/yarn.lock
Basically, our backend doesn't provide a dummy response to the related API endpoint. So we decide to use mock API instead
Related Library => https://www.npmjs.com/package/json-server
> init mock server using json server

- frontend/src/machines/billingMachine.ts
Init billing finite state machine flow or transition, from the beginning until the end of the final states.
*Additional Notes
This MR doesn't include the actions, guard, and services implementation. Moreover, this MR also doesn't include the context value of the machine.
Here's the related link => https://stately.ai/viz/eeb0a3dd-f0eb-4211-9dfa-5f26c985516c
> init billing finite state machine flow

- frontend/db.json
- frontend/package.json
changes
- add members mock
- add script to run json-server
> feat: add mock members

- frontend/src/components/BottomMenu.tsx
- frontend/src/containers/MembersPage/MemberList.tsx
- frontend/src/containers/MembersPage/MembersPage.tsx
changes
- rename `ButtonMenu` to `BottomMenu`
- add routing button
> fix: update bottom menu

- frontend/db.json
refactor data structure mock to be same with requirement
> refactor: mock api schema

- frontend/package.json
- frontend/src/containers/MembersPage/MemberList.tsx
- frontend/src/utils/fetcher.tsx
- frontend/yarn.lock
Changes
- adding `ts-pattern`
- change generator from `api.yaml` to `api.json`
- init `react-query` with `ts-pattern`
> feat: init member fetcher

- frontend/src/machines/paymentMachine.ts
This PR is just for the initialize payment machine, if the machine is correct, I will update the type and context
This is of the visualization of the payment machine https://stately.ai/registry/editor/share/5f25a033-d48b-4a67-a5e9-6444348650d8
> chore: init payment machine

- frontend/src/containers/Billings/BillingsPage.tsx
- frontend/src/containers/Billings/GeneralError.tsx
- frontend/src/machines/billings/billingMachine.ts
Implement a new action pattern & unused the action pattern matching implementation using TS Pattern.
> refactor billing machine with new action pattern

- frontend/src/machines/paymentMachine.ts
changes
- adding the type of Context, Event and machine state
- implement new action pattern
> chore: adding context and typing payment machine

- api.json
changes
- adding payments path for
- adding methods `GET` and `PUT` for payments path
- adding `GetPaymentListResponse`, `paymentByMemberId` and `paymentRequest` schema
> feat/adding payments by memberId API

- frontend/src/machines/paymentMachine.ts
- frontend/src/utils/fetcher.tsx
changes
- adding `paymentsApi` fetcher
- update typing Payment on Machine
- adding service
- update actions in several states
> feat: integrate service to payment machine

- frontend/server.js
- frontend/src/containers/Billings/BillingForm__FirstStep.tsx
- frontend/src/containers/Billings/BillingForm__SecondStep.tsx
- frontend/src/containers/Billings/BillingsPage.tsx
- frontend/src/containers/Billings/GeneralSuccess.tsx
- frontend/src/machines/billings/billingMachine.ts
So far, we've already retrieved the data into the billing list and billing form. And this Pull Request is dedicated to handling the billing data submission that we've already filled in the billing form through the BE. Since the BE team is not ready yet, so I use the mock API with the json-server.
- Handling creating billing data
- Handling editing billing data 
- Making GeneralSucces modal
- Adjust the mock API when we've already POST & PUT to the BE
- Update the BIllingForm property naming to camelCase
- Update the fetcher for Get billing detail
Here's the video link =>
https://drive.google.com/file/d/1DCCbXFLi0i0WYl-_iAC1Fxk49SUgmpZm/view?usp=sharing
> [feat] integrate billing machine to submit form

- frontend/db.json
- frontend/src/containers/MembersPage/MemberList.tsx
- frontend/src/containers/PaymentsPage/ConfirmationModal.tsx
- frontend/src/containers/PaymentsPage/PaymentList.tsx
- frontend/src/containers/PaymentsPage/PaymentsPage.tsx
- frontend/src/machines/paymentMachine.ts
- frontend/src/pages/payments/[memberId].tsx
changes
- adding `getServerSideProps` on member page
- update nameSpace `SubmittingPaymentError`
- update `MachineEvents` type
- using always on state `idle` and  `fetchingMemberSuccess`
- adding service submitPayment
- integration payment machine to the payment page
- adding `confirmationModal` component
https://user-images.githubusercontent.com/56879512/189466114-9daeca8a-0bc2-4a68-ac67-007178ecf2ca.mp4
> feat: integrate payment machine to component

- backend/go.sum
- backend/handler/api/response-builder.go
- backend/main.go
> feat: implement CORS middleware

- backend/core/module/billing-usecase.go
related issue : https://github.com/mnindrazaka/majer-otang/issues/77
> bugfix: fixing billings response

- backend/api.json
https://user-images.githubusercontent.com/70502753/193833394-e7cdb7c8-6170-47a5-ae28-c15cafa10393.mov
https://user-images.githubusercontent.com/70502753/193833478-d1cf53e2-430c-4a93-9c59-d9f73dbb169c.mov
https://github.com/mnindrazaka/majer-otang/issues/72
> fix wrong endpoint path for get billig detail

- frontend/src/containers/Billings/BillingList.tsx
https://github.com/mnindrazaka/majer-otang/issues/76
https://user-images.githubusercontent.com/70502753/193965125-d07e017d-84f2-48ce-b8f0-acc78342a275.mov
> ajdust billing list styling

- frontend/src/containers/Billings/BillingForm__FirstStep.tsx
https://github.com/mnindrazaka/majer-otang/issues/73
https://user-images.githubusercontent.com/70502753/194098430-e71fafea-604c-4dce-b7b6-6c2c5d958c68.mov
> implement form validation on billing form

- backend/api.json
- frontend/src/components/BottomMenu.tsx
- frontend/src/containers/Billings/BillingList.tsx
- frontend/src/containers/MembersPage/MembersPage.tsx
- frontend/src/containers/PaymentsPage/PaymentsPage.tsx
- frontend/src/machines/billings/billingMachine.ts
These changes include:
- Fix header styling 
- Fix update billing detail
https://user-images.githubusercontent.com/70502753/194443943-c8e7d988-1827-45c8-8f8a-190308672d03.mov
> fix edit billing detail and header styling

- frontend/src/containers/Billings/BillingList.tsx
- frontend/src/containers/PaymentsPage/PaymentList.tsx
related #67 
changes
- adding `toLocaleString` on payment and billing list
> feat: adding price formatting on billing and payment list

- frontend/.eslintrc.json
- frontend/package.json
- frontend/src/components/BottomMenu.tsx
- frontend/src/containers/Billings/BillingForm__FirstStep.tsx
- frontend/src/containers/Billings/BillingForm__SecondStep.tsx
- frontend/src/containers/Billings/BillingList.tsx
- frontend/src/containers/Billings/BillingsPage.tsx
- frontend/src/containers/Billings/GeneralError.tsx
- frontend/src/containers/Billings/GeneralSuccess.tsx
- frontend/src/containers/MembersPage/MemberList.tsx
- frontend/src/containers/MembersPage/MembersPage.tsx
- frontend/src/containers/PaymentsPage/ConfirmationModal.tsx
- frontend/src/containers/PaymentsPage/PaymentList.tsx
- frontend/src/containers/PaymentsPage/PaymentsPage.tsx
- frontend/src/machines/billings/billingMachine.ts
- frontend/src/machines/paymentMachine.ts
- frontend/src/pages/_app.tsx
- frontend/src/pages/payments/[memberId].tsx
- frontend/src/utils/fetcher.tsx
- frontend/yarn.lock
related #84 
changes
- adding plugin eslint rule [`simple-import-sort/imports`](https://github.com/lydell/eslint-plugin-simple-import-sort#readme)
> feat: adding eslint rules
